# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: daf451a033ac80f5530f10534981f76d895043b8019ebd8b4ba266b88408f202fa9e0bc6697526e88cb701e0e275243925525ac9c3dffdcf0e91ef33bf736e3b

test:
  secret_key_base: 28332f2cb981bde9539b4ca671d6137444e4cf6433ffaa5dfcca66eddaf62d93125e8e1bbbb755d229ca259db5a9f5d5cea1bd217e95d9bdbc4d4fbb3378e27d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
